import assert from 'node:assert/strict';
import { access, mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { test } from 'node:test';

const repository = resolve('.');
const generator = join(repository, '.agents/skills/arch-make-data-logical-diag/scripts/build-data-logical-diag.mjs');

async function put(root, path, contents)
{
    const target = join(root, path);
    await mkdir(resolve(target, '..'), { recursive: true });
    await writeFile(target, contents);
    return target;
}

function run(root, ...args)
{
    return spawnSync(process.execPath, [generator, '--root', root, ...args], {
        cwd: repository, encoding: 'utf8', windowsHide: true
    });
}

async function cleanFixture()
{
    await mkdir(join(repository, '.cache'), { recursive: true });
    const root = await mkdtemp(join(repository, '.cache/data-diagram-fixture-'));
    await put(root, 'src/game/state/gameStateSnapshot.ts', [
        "import type { ChildState } from './childState';",
        'export interface GameStateSnapshot {',
        '    readonly schemaVersion: 1;',
        '    readonly child: ChildState;',
        '    readonly children: readonly ChildState[];',
        '}', ''
    ].join('\n'));
    await put(root, 'src/game/state/childState.ts', [
        "export type ChildKind = 'one' | 'two';",
        'export interface ChildState {',
        '    readonly id: string;',
        '    readonly kind: ChildKind;',
        '    readonly note: string | null;',
        '}', ''
    ].join('\n'));
    await put(root, 'src/unrelated.ts', 'export interface UnrelatedState { value: number }\n');
    const nodes = [
        ['src/game/state/gameStateSnapshot#GameStateSnapshot', 'GameStateSnapshot', 'src/game/state/gameStateSnapshot', 'interface', 'data'],
        ['src/game/state/childState#ChildState', 'ChildState', 'src/game/state/childState', 'interface', 'data'],
        ['src/game/state/childState#ChildKind', 'ChildKind', 'src/game/state/childState', 'type', 'data'],
        ['src/unrelated#UnrelatedState', 'UnrelatedState', 'src/unrelated', 'interface', 'model']
    ].map(([id, name, module, kind, layer]) => ({ id, name, module, kind, layer }));
    const edges = [
        { from: nodes[0].id, to: nodes[1].id, kind: 'imports' },
        { from: nodes[1].id, to: nodes[2].id, kind: 'uses' }
    ];
    await put(root, 'context/foundation/code-graph.json', JSON.stringify({
        schemaVersion: 1, generator: 'arch-make-code-graph', sourceRoot: 'src', nodes, edges
    }, null, 2));
    return root;
}

test('generates deterministic reachable entities, fields, links and cardinalities', async () => {
    const root = await cleanFixture();
    const first = run(root);
    assert.equal(first.status, 0, first.stderr);
    assert.match(first.stdout, /Diagram CREATED .* entities 3, findings 0/);
    const output = join(root, 'context/foundation/data-logical-diagram.md');
    const content = await readFile(output, 'utf8');
    assert.match(content, /^<!-- generated by arch-make-data-logical-diag -->/);
    assert.match(content, /classDiagram/);
    assert.match(content, /GameStateSnapshot "1" \*-- "\*" ChildState : children/);
    assert.match(content, /ChildState \| note \| `string \\\| null` \| 0\.\.1/);
    assert.doesNotMatch(content, /UnrelatedState/);
    assert.match(content, /No findings\./);
    const second = run(root);
    assert.equal(second.status, 0, second.stderr);
    assert.match(second.stdout, /Diagram UNCHANGED/);
    const checked = run(root, '--check');
    assert.equal(checked.status, 0, checked.stderr);
    assert.match(checked.stdout, /Diagram CURRENT/);
});

test('writes partial findings normally and never writes in check mode', async () => {
    const root = await cleanFixture();
    await put(root, 'src/game/state/childState.ts', [
        'export interface ChildState {',
        '    id: string;',
        '    readonly callback: () => void;',
        '    update(): void;',
        '}',
        "export type ChildKind = 'one';",
        ''
    ].join('\n'));
    const checked = run(root, '--check');
    assert.equal(checked.status, 2);
    assert.match(checked.stderr, /REFACTOR_REQUIRED/);
    await assert.rejects(access(join(root, 'context/foundation/data-logical-diagram.md')), error => error.code === 'ENOENT');
    const written = run(root);
    assert.equal(written.status, 2);
    const content = await readFile(join(root, 'context/foundation/data-logical-diagram.md'), 'utf8');
    assert.match(content, /REFACTOR_REQUIRED src\/game\/state\/childState\.ts:2 state field ChildState\.id must be readonly/);
    assert.match(content, /not JSON-safe/);
    assert.match(content, /contains behavior method/);
});

test('rejects stale graphs, malformed graphs, and unowned output without force', async () => {
    const staleRoot = await cleanFixture();
    await put(staleRoot, 'src/game/state/extraState.ts', 'export interface ExtraState { readonly value: number }\n');
    const stale = run(staleRoot);
    assert.equal(stale.status, 2);
    assert.match(stale.stderr, /STALE_GRAPH/);

    const malformedRoot = await cleanFixture();
    await put(malformedRoot, 'context/foundation/code-graph.json', '{broken');
    const malformed = run(malformedRoot);
    assert.equal(malformed.status, 2);
    assert.match(malformed.stderr, /Malformed code graph JSON/);

    const unownedRoot = await cleanFixture();
    const output = await put(unownedRoot, 'context/foundation/data-logical-diagram.md', '# Hand written\n');
    const refused = run(unownedRoot);
    assert.equal(refused.status, 2);
    assert.match(refused.stderr, /Refusing to overwrite unowned diagram/);
    assert.equal(await readFile(output, 'utf8'), '# Hand written\n');
    const forced = run(unownedRoot, '--force');
    assert.equal(forced.status, 0, forced.stderr);
});
