import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync, spawnSync } from 'node:child_process';
import { cp, mkdir, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

test('scaffold dry-run, validation, overwrite refusal and generated TypeScript integration', async () => {
    const root = resolve('.');
    await mkdir('.cache', { recursive: true });
    const fixture = await mkdtemp(join(root, '.cache/object-scaffold-'));
    await mkdir(join(fixture, 'src/game/scenes'), { recursive: true });
    await cp('src/game/objects/_shared', join(fixture, 'src/game/objects/_shared'), { recursive: true });
    await cp('src/game/visual', join(fixture, 'src/game/visual'), { recursive: true });
    await writeFile(join(fixture, 'src/game/scenes/gameScene.ts'), "import { Scene } from 'phaser';\nexport class Game extends Scene {}\n");
    await cp('src/viteEnv.d.ts', join(fixture, 'src/viteEnv.d.ts'));
    const script = join(root, '.agents/skills/utils-add-object-to-scene/scripts/scaffold.mjs');
    const run = args => spawnSync(process.execPath, [script, ...args], { cwd: fixture, encoding: 'utf8', windowsHide: true });
    for (const args of [['../escape'], ['probe','--scene','../Game'], ['probe','--scene','Missing'], ['probe','--physics','unknown'], ['probe','--shape','circle']]) assert.notEqual(run(args).status, 0);
    assert.equal(run(['probe','--dry-run']).status, 0);
    assert.deepEqual(await readdir(join(fixture,'src/game/objects')), ['_shared']);
    assert.equal(run(['probe','--physics','dynamic','--shape','circle']).status, 0);
    const definition = await readFile(join(fixture,'src/game/objects/probe/definition.ts'),'utf8');
    assert.notEqual(run(['probe']).status, 0);
    assert.equal(await readFile(join(fixture,'src/game/objects/probe/definition.ts'),'utf8'), definition);
    assert.equal(run(['decoration']).status, 0);
    assert.equal(run(['obstacle','--physics','static']).status, 0);
    await mkdir(join(fixture, 'src/game/scenes/Folder.ts'));
    assert.notEqual(run(['not-created', '--scene', 'Folder']).status, 0, 'a directory is not a scene');
    await mkdir(join(fixture, 'src/game/objects/alias'));
    const alias = join(fixture, 'src/game/objects/alias/definition.ts');
    await writeFile(alias, "export const definition = { id: 'duplicate-object' };\n");
    assert.notEqual(run(['duplicate-object']).status, 0, 'existing IDs in other modules must be rejected');
    await writeFile(alias, "export const definition = { id: 'alias', assets: [{ key: 'object:duplicate-key:image' }] };\n");
    assert.notEqual(run(['duplicate-key', '--dry-run']).status, 0, 'duplicate key prefixes must fail even during dry-run');
    assert.deepEqual((await readdir(join(fixture, 'src/game/objects'))).sort(), ['_shared', 'alias', 'decoration', 'obstacle', 'probe']);
    await writeFile(join(fixture, 'src/game/scenes/gameScene.ts'), "import { Scene } from 'phaser';\nimport { Probe } from '../objects/probe/probe';\nexport class Game extends Scene { create () { const probe = new Probe(this, { x: 50, y: 50 }); probe.update(0, 16); } }\n");
    await writeFile(join(fixture,'tsconfig.json'), JSON.stringify({ extends: join(root,'tsconfig.json'), include: ['src'] }));
    execFileSync(process.execPath, [join(root,'node_modules/typescript/bin/tsc'),'--noEmit','-p',join(fixture,'tsconfig.json')], { encoding:'utf8', windowsHide:true });
});
