import type { Game } from 'phaser';
import { createAudioSettingsPort } from './adapters/audioSettingsAdapter';
import { createDisplayPort } from './adapters/displayAdapter';
import { createGameControlsPort } from './adapters/gameControlsAdapter';
import { createRunStatusPort } from './adapters/runStatusAdapter';
import { createLandingStatusPort } from './adapters/landingStatusAdapter';
import { mountAudioControls } from './components/audioControls';
import { mountDisplayControls } from './components/displayControls';
import { mountGameMenu } from './components/gameMenu';
import { mountRunStatus } from './components/runStatus';
import { mountLandingStatus } from './components/landingStatus';
import { mountAuthControls } from './components/authControls';
import type { AuthPort } from '../game/application/auth/auth';
import type { TelemetryPort } from '../game/application/telemetry/telemetry';
import type { UiHandle } from './contracts';

export function setupApplicationUi (root: HTMLElement, game: Game, auth: AuthPort, telemetry: TelemetryPort): UiHandle
{
    const container = root.querySelector<HTMLElement>('#game-container');
    if (!container) throw new Error('Missing game container.');
    game.canvas.tabIndex = 0;
    const audio = mountAudioControls(root, createAudioSettingsPort(game));
    const controlsPort = createGameControlsPort(game);
    const menuControls = mountGameMenu(root, controlsPort);
    const displayPort = createDisplayPort(game, root, container);
    const display = mountDisplayControls(root, displayPort, active => game.events.emit('fullscreen-change', active));
    const toggleFullscreen = (): void => { void displayPort.toggleFullscreen(); };
    game.events.on('toggle-fullscreen', toggleFullscreen);
    const runStatus = mountRunStatus(root, createRunStatusPort(game));
    game.registry.set('telemetry', telemetry);
    const landingStatus = mountLandingStatus(root, createLandingStatusPort(game));
    const authControls = mountAuthControls(root, auth);
    const mainMenu = root.querySelector<HTMLElement>('#main-menu');
    const mainMenuNewGame = root.querySelector<HTMLButtonElement>('#main-menu-new-game');
    const debugMenu = root.querySelector<HTMLElement>('#debug-menu');
    const debugClose = root.querySelector<HTMLButtonElement>('#debug-menu-close');
    const touchControlsToggle = root.querySelector<HTMLButtonElement>('#debug-touch-controls-toggle');
    const mouseMovementToggle = root.querySelector<HTMLButtonElement>('#debug-mouse-movement-toggle');
    const boosterToggle = root.querySelector<HTMLButtonElement>('#debug-booster-toggle');
    const teleportSeroton = root.querySelector<HTMLButtonElement>('#debug-teleport-seroton');
    const teleportLactozis = root.querySelector<HTMLButtonElement>('#debug-teleport-lactozis-7c');
    const teleportMasloPrime = root.querySelector<HTMLButtonElement>('#debug-teleport-maslo-prime');
    if (!mainMenu || !mainMenuNewGame || !debugMenu || !debugClose || !touchControlsToggle || !mouseMovementToggle || !boosterToggle || !teleportSeroton || !teleportLactozis || !teleportMasloPrime) throw new Error('Missing game menu controls.');
    const showMainMenu = (): void => { mainMenu.hidden = false; };
    const hideMainMenu = (): void => { mainMenu.hidden = true; };
    const startNewGame = (): void => { game.events.emit('start-new-game'); };
    mainMenuNewGame.addEventListener('click', startNewGame);
    game.events.on('main-menu-open', showMainMenu);
    game.events.on('main-menu-close', hideMainMenu);
    const updateOrientationPause = (): void => controlsPort.setOrientationPaused(displayPort.getSnapshot().mobile && displayPort.getSnapshot().portrait);
    const unsubscribeOrientation = displayPort.subscribe(updateOrientationPause);
    let touchControlsEnabled = false;
    let mouseMovementEnabled = true;
    let boosterEnabled = false;
    const renderDebugToggles = (): void => {
        touchControlsToggle.textContent = `Show touch screen controls: ${touchControlsEnabled ? 'ON' : 'OFF'}`;
        touchControlsToggle.setAttribute('aria-pressed', String(touchControlsEnabled));
        mouseMovementToggle.textContent = `Mouse movement: ${mouseMovementEnabled ? 'ON' : 'OFF'}`;
        mouseMovementToggle.setAttribute('aria-pressed', String(mouseMovementEnabled));
        boosterToggle.textContent = `Booster enable: ${boosterEnabled ? 'ON' : 'OFF'}`;
        boosterToggle.setAttribute('aria-pressed', String(boosterEnabled));
    };
    const closeDebugMenu = (): void => { debugMenu.hidden = true; game.canvas.focus(); };
    const openDebugMenu = (): void => { debugMenu.hidden = false; renderDebugToggles(); debugClose.focus(); };
    const toggleTouchControls = (): void => { touchControlsEnabled = !touchControlsEnabled; game.events.emit('debug-touch-controls', touchControlsEnabled); renderDebugToggles(); };
    const toggleMouseMovement = (): void => { mouseMovementEnabled = !mouseMovementEnabled; game.events.emit('debug-mouse-movement', mouseMovementEnabled); renderDebugToggles(); };
    const toggleBooster = (): void => { boosterEnabled = !boosterEnabled; game.events.emit('debug-booster', boosterEnabled); renderDebugToggles(); };
    const teleportTo = (planetId: string): void => { game.events.emit('debug-teleport-to-planet', planetId); closeDebugMenu(); };
    const teleportToSeroton = (): void => { teleportTo('seroton'); };
    const teleportToLactozis = (): void => { teleportTo('lactozis-7c'); };
    const teleportToMasloPrime = (): void => { teleportTo('maslo-prime'); };
    const resetDebugControls = (): void => {
        touchControlsEnabled = false;
        mouseMovementEnabled = true;
        boosterEnabled = false;
        debugMenu.hidden = true;
        renderDebugToggles();
    };
    const debugKeyDown = (event: KeyboardEvent): void => {
        if (event.key.toLowerCase() !== 'd' || event.repeat || event.target instanceof Element && event.target.closest('[data-game-input="ignore"]')) return;
        if (debugMenu.hidden) openDebugMenu();
        else closeDebugMenu();
    };
    debugClose.addEventListener('click', closeDebugMenu);
    touchControlsToggle.addEventListener('click', toggleTouchControls);
    mouseMovementToggle.addEventListener('click', toggleMouseMovement);
    boosterToggle.addEventListener('click', toggleBooster);
    teleportSeroton.addEventListener('click', teleportToSeroton);
    teleportLactozis.addEventListener('click', teleportToLactozis);
    teleportMasloPrime.addEventListener('click', teleportToMasloPrime);
    game.events.on('debug-controls-reset', resetDebugControls);
    window.addEventListener('keydown', debugKeyDown);
    const returnToGame = (): void => {
        const focused = document.activeElement;
        if (focused instanceof HTMLElement && focused.closest('[data-game-input="ignore"]')) focused.blur();
    };
    game.canvas.addEventListener('pointerdown', returnToGame);
    let destroyed = false;
    const handle: UiHandle = {
        destroy: () => {
            if (destroyed) return;
            destroyed = true;
            audio.destroy();
            menuControls.destroy();
            display.destroy();
            runStatus.destroy();
            landingStatus.destroy();
            authControls.destroy();
            auth.destroy();
            telemetry.destroy();
            unsubscribeOrientation();
            mainMenuNewGame.removeEventListener('click', startNewGame);
            game.events.off('main-menu-open', showMainMenu);
            game.events.off('main-menu-close', hideMainMenu);
            debugClose.removeEventListener('click', closeDebugMenu);
            touchControlsToggle.removeEventListener('click', toggleTouchControls);
            mouseMovementToggle.removeEventListener('click', toggleMouseMovement);
            boosterToggle.removeEventListener('click', toggleBooster);
            teleportSeroton.removeEventListener('click', teleportToSeroton);
            teleportLactozis.removeEventListener('click', teleportToLactozis);
            teleportMasloPrime.removeEventListener('click', teleportToMasloPrime);
            game.events.off('debug-controls-reset', resetDebugControls);
            game.events.off('toggle-fullscreen', toggleFullscreen);
            window.removeEventListener('keydown', debugKeyDown);
            game.canvas.removeEventListener('pointerdown', returnToGame);
            game.events.off('destroy', handle.destroy);
        }
    };
    game.events.once('destroy', handle.destroy);
    return handle;
}
