export const displayLabels = {
    fullscreen: 'Fullscreen',
    closeFullscreen: 'X',
    rotateToPlay: 'Rotate your device to play.',
    rotateOrFullscreen: 'Rotate your device or select "Fullscreen".',
    fullscreenFailed: 'Failed to enter fullscreen. You can still play by rotating your device.',
    orbitCaptured: 'ORBIT CAPTURED',
    proceedToLand: 'PROCEED TO LAND',
    orbitAvailable: 'ORBIT AVAILABLE',
    leavingPlanet: 'LEAVING PLANET',
    landOn: 'LAND ON',
    landed: 'LANDED',
    landedSuffix: '— LANDED',
    launch: 'LAUNCH',
    pausedTime: 'Time is paused while landed.',
    marketCredits: 'Credits', marketCargo: 'Cargo', marketQuantity: 'Trade quantity', marketQuote: 'Quote',
    marketPostTradeStock: 'Stock after trade', marketNextPrice: 'Next unit price', marketConfirm: 'CONFIRM TRADE',
    marketBuy: 'BUY', marketSell: 'SELL', marketNoTrade: 'SELECT A QUANTITY', marketCashShortfall: 'Insufficient credits:',
    supplies: 'Supplies', alloys: 'Alloys', medicines: 'Medicines'
} as const;
