export const displayLabels = {
    signInWithGoogle: 'Sign in with Google',
    signOut: 'Sign out',
    unsigned: 'Unsigned',
    authUnavailable: 'Sign-in is unavailable: configure Supabase public URL and publishable key.',
    authError: 'Sign-in failed. Please try again.',
    fullscreen: 'Fullscreen',
    closeFullscreen: 'X',
    rotateToPlay: 'Rotate your device to play.',
    rotateOrFullscreen: 'Rotate your device or select "Fullscreen".',
    fullscreenFailed: 'Failed to enter fullscreen. You can still play by rotating your device.',
    orbitCaptured: 'ORBIT CAPTURED',
    proceedToLand: 'PROCEED TO LAND',
    orbitAvailable: 'ORBIT AVAILABLE',
    leavingPlanet: 'LEAVING PLANET',
    landOn: 'LAND ON',
    landed: 'LANDED',
    landedSuffix: '— LANDED',
    launch: 'LAUNCH',
    landedOn: 'Landed on', market: 'Market', back: 'BACK', shipyard: 'Shipyard', shipyardUnavailable: 'Shipyard unavailable',
    marketCredits: 'Credits', marketCargo: 'Cargo', marketQuantity: 'Trading', marketQuote: 'Total trade value',
    marketConfirm: 'CONFIRM TRADE',
    marketBuy: 'BUY', marketSell: 'SELL', marketNoTrade: 'SELECT A QUANTITY', marketCashShortfall: 'Insufficient credits:',
    planetStock: 'Planet stock', playerStock: 'Ship inventory', produces: 'Produces', consumes: 'Consumes', supply: 'Supply',
    averageBuyPrice: 'Average buy price', inBudget: 'IN BUDGET', outOfBudget: 'OUT OF BUDGET',
    tradeResult: 'Trade result:', profit: 'PROFIT', loss: 'LOSS',
    supplies: 'Supplies', alloys: 'Alloys', medicines: 'Medicines'
} as const;
